# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56dade921300064dccfaa87e91f7520d9bdd6d1acff25ce7632400888cfff4c96c5b9e24be1d8ba1ae9076d21f24a994d552efdc966408b8bec12edbb505cdb5

test:
  secret_key_base: 44cbe5345454a946a4b2f7831fdb3863ee5dba2aaf392acdda73426938f76acb2bebb1b5c3544ce56386cfcea70e9f19f6b5914d1d5ef2c5bf9752ea11881546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
